#
# Copyright © Nikita (DeethzzCoder) Knyazev [vk.com/deethzzcoder/]
#

name: DeethEasterEggs
version: 0.5
main: com.deethzzcoder.deetheastereggs.DeethEasterEggsPlugin

commands:
  eastereggs:
    aliases: [easteregg]
